services:
  api:
    build: 
      context: .
      dockerfile: EClaim.API/Dockerfile
    container_name: eclaim_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379,abortConnect=false,connectTimeout=15000
    depends_on:
      - redis
    networks:
      - eclaimnet

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eclaimnet

networks:
  eclaimnet:

volumes:
  redis_data:
