version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: EClaim.API/Dockerfile
    container_name: eclaim_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
